version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: paleoclimate
      POSTGRES_PASSWORD: paleoclimate
      POSTGRES_DB: paleoclimate
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      - FASTAPI_ENV=production
    ports:
      - "8002:8002"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
