name: paleoclimate
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi=0.65.2
  - uvicorn=0.14.0
  - sqlalchemy=1.4.22
  - pydantic=1.8.2
  - pandas
  - pylint
  - flake8
  - black
  - autopep8
  - python-multipart
  - openpyxl
  - loguru
  - pip:
    - pytest