name: paleoclimate
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic
  - python=3.9
  - fastapi=0.65.2
  - uvicorn=0.14.0
  - sqlalchemy=1.4.22
  - pydantic=1.9.3
  - pydantic_settings
  - pandas
  - geopandas
  - matplotlib
  - folium
  - pylint
  - flake8
  - black
  - autopep8
  - python-multipart
  - openpyxl
  - loguru
  - psycopg2-binary
  - pip7
  - diskcache
  - pip:
      - pytest
      - pytest-cov
      - tox
      - sphinx
      - sphinx_rtd_theme
