"""Add weights to Point model

Revision ID: 32f78ed12cae
Revises: 8e4526db36a6
Create Date: 2024-10-30 03:16:32.645032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f78ed12cae'
down_revision: Union[str, None] = '8e4526db36a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('basin', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('lat', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('long', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('climate', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='points_pkey')
    )
    # ### end Alembic commands ###
